#! /bin/sh

bspc config border_width        2
bspc config window_gap         20
bspc config top_padding        22
bspc config bottom_padding      0.5
bspc config right_padding       0
bspc config left_padding	      0
bspc config border_radius			  4

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5
bspc monitor Virtual1 -d one two three four five
#bspc monitor -d ⮘ ⮙ ⮚

#feh --bg-fill ~/Pictures/Wallpapers/1412881718523.jpg
hsetroot -solid "#383c4c"

bspc config focused_border_color "#828595"
bspc config normal_border_color "#0f1116"
bspc config active_border_color "#818594"
bspc config focused_locked_border_color "#828595"
bspc config normal_locked_border_color "#0f1116"
bspc config active_locked_border_color "#828595"

panel &
