#! /bin/sh

bspc config border_radius				3
bspc config border_width        2
bspc config window_gap         14
bspc config top_padding        12
bspc config bottom_padding      0.5
bspc config right_padding       0
bspc config left_padding	      0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d one two three four five

hsetroot -solid "#383c4c"

bspc config focused_border_color "#828595"
bspc config normal_border_color "#0F1116"
bspc config active_border_color "#828595"
bspc config focused_locked_border_color "#828595"
bspc config normal_locked_border_color "#828595"
bspc config active_locked_border_color "#828595"

panel &
